### ISSUE TITLE
AWS Policy, and ThingType

### ISSUE THREAD

**Issue by armandr** [mahavirj/esp-bootstrap#1]
Hi Mahavir! 

I'm trying to replicate the setup and it's a bit of a guess work on the AWS console. Possible you could also share the AWS Policy and ThingType?

**Comment by kedars** [comment]
For the simplest case, you can get started with

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```

I haven't defined a specific thing-type

**Comment by mahavirj** [comment]
@armandr Were you able to replicate setup at your end?

**Comment by armandr** [comment]
Yes I was able run the sample with my own certs and endpoint.  Thank you @mahavirj and @kedars.
